sudo: required 
services:
  - docker   




before_install:
  - docker build -t jstryngs/docker-react -f Dockerfile.dev .     



script:
  - docker run -e CI=true jstryngs/docker-react npm run test


deploy:
  provider: elaseticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-039248412063"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"


