sudo: required 
services:
  - docker   




before_install:
  - docker build -t jstryngs/docker-react -f Dockerfile.dev .     



script:
  - docker run jstryngs/docker-react npm run test -- --coverage


